spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/psyweb
    username: psyweb
    password: psyweb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true